# TASCA M5 T01

In [1]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind

In [2]:
# import dataset
uefa = pd.read_csv('C:\Lligues_europees_UEFA.csv', sep =';'  ,encoding = "ISO-8859-1")

In [3]:
uefa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Rk               98 non-null     int64
 1   Squad            98 non-null     object
 2   Country          98 non-null     object
 3   LgRk             98 non-null     int64
 4   MP               98 non-null     int64
 5   W                98 non-null     int64
 6   D                98 non-null     int64
 7   L                98 non-null     int64
 8   GF               98 non-null     int64
 9   GA               98 non-null     int64
 10  GD               98 non-null     int64
 11  Pts              98 non-null     int64
 12  Pts/G            98 non-null     float64
 13  xG               98 non-null     float64
 14  xGA              98 non-null     float64
 15  xGD              98 non-null     float64
 16  xGD/90           98 non-null     float64
 17  Last 5           98 non-null     object
 18  Attendance       98 non-null     int64
 19  Top Team Scorer  98 non-null     object
 20  Goalkeeper       98 non-null     object
dtypes: float64(5), int64(11), object(5)
memory usage: 16.2+ KB

In [4]:
uefa.shape

(98, 21)

In [5]:
uefa.head()

,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,...,Pts,Pts/G,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper
0,1,Manchester City,ENG,1,37,28,6,3,96,24,...,90,2.43,86.1,26.8,59.3,1.60,W W W W D,52739,Kevin De Bruyne - 15,Ederson
1,2,Liverpool,ENG,2,36,26,8,2,89,24,...,86,2.39,84.6,33.1,51.4,1.43,W W W D W,53367,Mohamed Salah - 22,Alisson
2,3,Real Madrid,ESP,1,37,26,7,4,80,31,...,85,2.30,73.0,45.8,27.2,0.73,W W L W D,40624,Karim Benzema - 27,Thibaut Courtois
3,4,Bayern Munich,GER,1,34,24,5,5,97,37,...,77,2.26,88.1,37.1,51.0,1.50,W W L D D,33176,Robert Lewandowski - 35,Manuel Neuer
4,5,Paris S-G,FRA,1,37,25,8,4,85,36,...,83,2.24,71.6,38.1,33.4,0.90,W D D D W,41188,Kylian Mbappé - 25,Keylor Navas

Rk = ranking
Squad = equip
Country = país
LgRk = 
MP = partits jugats
W = partits guanyats
D = partits empatats
L = partits perduts
GF = Gols marcats
GA = Gols en contra
GD =  diferencia de gols (gf-ga)
pts = punts
pts/ G = punts / partits guanyats
xG = probabilitat gol esperat, probabilitat de que un tir produeixi un gol.
xGA = probabilitat de gol esperat en contra, probabilitat que un tir en contra produeixi gol.
xGD = diferència entre gols anotats esperats i els fallats esperats
xGD/90 = diferència entre gols anotats esperats i fallats esperats en 90 minuts.
Last 5 = resultat dels últims 5 partits.
Attendance = quantitat de gent que va a l'estadi a veure el partit.
Top Team Scorer = jugador més golejador
Goalkepper = porter

In [6]:
uefa.describe()

,Rk,LgRk,MP,W,D,L,GF,GA,GD,Pts,Pts/G,xG,xGA,xGD,xGD/90,Attendance
count,98.000000,98.000000,98.000000,98.000000,98.000000,98.00000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000
mean,49.500000,10.316327,36.306122,13.448980,9.408163,13.44898,50.877551,50.877551,0.000000,49.734694,1.370204,48.653061,48.645918,-0.005102,0.000918,24239.857143
std,28.434134,5.706926,1.152390,5.747474,2.903381,5.12347,16.102933,13.634602,26.501896,16.166371,0.443903,12.453950,9.812481,19.992506,0.551414,14874.171842
min,1.000000,1.000000,34.000000,3.000000,3.000000,2.00000,23.000000,24.000000,-56.000000,18.000000,0.530000,28.200000,26.800000,-40.400000,-1.090000,5870.000000
25%,25.250000,5.250000,36.000000,9.000000,7.000000,10.00000,39.000000,40.000000,-17.750000,37.000000,1.000000,39.100000,41.300000,-13.575000,-0.365000,12355.500000
50%,49.500000,10.000000,37.000000,13.000000,9.000000,13.00000,47.000000,50.000000,-1.000000,46.000000,1.300000,46.450000,47.750000,-1.100000,-0.030000,20491.000000
75%,73.750000,15.000000,37.000000,17.000000,11.000000,17.00000,60.000000,59.000000,17.250000,61.750000,1.695000,55.550000,54.700000,12.800000,0.355000,32382.000000
max,98.000000,20.000000,37.000000,28.000000,16.000000,26.00000,97.000000,89.000000,72.000000,90.000000,2.430000,88.100000,73.300000,59.300000,1.600000,73150.000000

* count: suma dels valors no nuls de cada atribut.
* mean: valor mig de l'atribut.
* std: desviació estándar dels valors d'aquell atribut.
* min: valor mínim de l'atribut.
* 25%,50%,75% : Valors corresponents amb els percentils.
* max: valor màxim per cada atribut

In [7]:
# miro si hi ha elements duplicats
uefa_clean = uefa.drop_duplicates()
if len(uefa_clean) == len(uefa):
    print("No hi ha elements duplicats")
else:
    print("Hi ha elements duplicats")

No hi ha elements duplicats

In [8]:
# comprovo si hi ha elements nuls
uefa.isnull()

,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,...,Pts,Pts/G,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
94,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
95,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
# comprovo si hi ha elements nuls.
(uefa.isnull().sum())*100 / len(uefa)

Rk                 0.0
Squad              0.0
Country            0.0
LgRk               0.0
MP                 0.0
W                  0.0
D                  0.0
L                  0.0
GF                 0.0
GA                 0.0
GD                 0.0
Pts                0.0
Pts/G              0.0
xG                 0.0
xGA                0.0
xGD                0.0
xGD/90             0.0
Last 5             0.0
Attendance         0.0
Top Team Scorer    0.0
Goalkeeper         0.0
dtype: float64

## Exercici 1
Descarrega el dataset adjunt de dades oficials de la UEFA i selecciona un atribut del conjunt de dades. Calcula el p-valor i digues si rebutja la hipòtesi nul-la agafant un alfa de 5%

In [10]:
#H0: la mostra té una distribució gaussiana
#H1: la mostra no té una distribució gaussiana
#trio latribut de partits guanyats per veure si té una distribució gaussiana

from scipy.stats import shapiro
data = uefa[['W']]
stat, p = shapiro(data)
print('stat=%.3f, p=%.3f' %(stat, p))
if p > 0.05:
      print('Probablement tenen una distribució gaussiana, acceptem hipotesi nul-la')
else:
      print('Probablement no tenen una distribució gaussiana, rebutjem hipotesi nul-la')

stat=0.965, p=0.011
Probablement no tenen una distribució gaussiana, rebutjem hipotesi nul-la

## Exercici 2
Amb el mateix dataset selecciona dos altres atributs del conjunt de dades. Calcula els p-valors i digues si rebutgen la hipòtesi nul-la agafant un alfa de 5%.

In [11]:
# H0: les mitjes de les mostres són iguals
# H1: les mitjes de les mostres són desiguals
# trio els atributs de gols ficats i gols en contra.

from scipy.stats import ttest_ind
data1 = uefa[['GF']]
data2 = uefa[['GA']]
stat, p = ttest_ind(data1, data2)
print('stat=%.3f, p=%.3f' % (stat,p))
if p > 0.05:
    print('les mitjes de les mostres són iguals, acceptem hipotesi nul-la')
else:
    print('les mitjes dee les mostres són desiguals, rebutjem hipotesi nul-la')

stat=0.000, p=1.000
les mitjes de les mostres són iguals, acceptem hipotesi nul-la

## Exercici 3

Continua amb el conjunt de dades adjunt i selecciona tres atributs del conjunt de dades. Calcula el p-valor i digues si rebutja la hipòtesi nul-la agafant un alfat del 5%

In [12]:
# H0: les mitjes de les mostres són iguals
# H1: les mitjes de les mostres són desiguals
# per fer aquest exercici triu l'anàlisi ANOVA perque són més de dos atributs
# trio els atributs de gols marcats, partits guanyats i 
from scipy.stats import f_oneway
data1 = uefa[['D']]
data2 = uefa[['L']]
data3 = uefa[['xGA']]
stat, p = f_oneway(data1, data2, data3)
print('stat=%.3f, p=%.3f' % (stat, p))

if p > 0.5:
    print('Probablement tenen la mateixa distribució, acceptem hipotesi nul-la')
else:
    print('Probablement tenen una distribució diferent, rebutjem hipotesi nul-la')

stat=1045.651, p=0.000
Probablement tenen una distribució diferent, rebutjem hipotesi nul-la